#ssh-keygen -N "" -t rsa -f ./id_rsa
#ssh-copy-id -i ./id_rsa.pub -p<port> <user>@<destination>
#ssh -i ./id_rsa -p<Port> <user>@<destination>

version: '3.1'
services:
  app:
    image: nginx:1.25-alpine
    tty: true
    ports:
      - 80:80
      - 50001-50099:50001-50099
    volumes:
      - ./id_rsa:/sshkey:ro
      - ./docker-cmd.sh:/docker-cmd.sh:ro
    environment:
      - SSH_SERVER=<destination>
      - REMOTE_ADDRESS=127.0.0.1
      - SSH_PORT=<port>
      - SSH_USER=<user>
    command: sh /docker-cmd.sh
    logging:
      options:
        max-size: 1g
